// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VRTrackingApp.Data.Models;

#nullable disable

namespace VRTrackingApp.Data.Migrations
{
    [DbContext(typeof(VRTrackingAppContext))]
    [Migration("20260713011624_AddRemediationJob")]
    partial class AddRemediationJob
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VRTrackingApp.Data.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveDirectoryComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Application")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationSystemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetCriticality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetStatus")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Availability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackupDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackupOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackupSchedule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BiaCriticality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Confidentiality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CpuCoreCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CriticalResources")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CriticalRoles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Criticality2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataReplicationFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Datacenter")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DisasterRecoveryRequired")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrSetupDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DriveCount")
                        .HasColumnType("int");

                    b.Property<string>("Environment")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExternalPoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalPocRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinancialImpact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupLandscape")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hardware")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HardwareDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Integrity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterDependencies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalPoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MinimumHardware")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinimumHardware2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinimumItResources")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NonFinancialImpact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("OffPeakTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnsiteResourceBackup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OtherItResources")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutageImpact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeakTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PocRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrioritizeResourceRecovery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RamGb")
                        .HasColumnType("int");

                    b.Property<string>("RedundancyDrDc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RedundancyPrimaryDc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegulatoryImpact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rpo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerIpAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Software")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SystemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalDiskSpaceGb")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vendor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetStatus");

                    b.HasIndex("Category");

                    b.HasIndex("Datacenter");

                    b.HasIndex("Environment");

                    b.HasIndex("HostName");

                    b.HasIndex("IpAddress");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.AssetAuditTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PerformedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("PerformedAt");

                    b.HasIndex("PerformedByUserId");

                    b.ToTable("AssetAuditTrails");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.AssetFieldChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetAuditTrailId")
                        .HasColumnType("int");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("AssetAuditTrailId");

                    b.ToTable("AssetFieldChanges");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.AssetHost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HostName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScanUploadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("IpAddress");

                    b.HasIndex("ScanUploadId");

                    b.ToTable("AssetHosts");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.ExceptionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("VulnerabilityInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("VulnerabilityInstanceId")
                        .IsUnique();

                    b.ToTable("ExceptionRecords");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.RemediationAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvidenceFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExceptionExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PerformedById")
                        .HasColumnType("int");

                    b.Property<int?>("PerformedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VulnerabilityInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("PerformedById");

                    b.HasIndex("VulnerabilityInstanceId");

                    b.ToTable("RemediationActions");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.RemediationJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCriticalAsset")
                        .HasColumnType("bit");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Log")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PatchId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RequestedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ResultSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TargetHost")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("VulnerabilityInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("State");

                    b.HasIndex("VulnerabilityInstanceId");

                    b.ToTable("RemediationJobs");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.ScanUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScanCycleLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ScanDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UploadedById")
                        .HasColumnType("int");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScanDate");

                    b.HasIndex("SourceType");

                    b.HasIndex("UploadedById");

                    b.ToTable("ScanUploads");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.UploadAuditTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PerformedById")
                        .HasColumnType("int");

                    b.Property<int?>("PerformedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ScanUploadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerformedById");

                    b.HasIndex("ScanUploadId");

                    b.ToTable("UploadAuditTrails");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("MfaSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.VulnerabilityFinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cve")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("CvssV2BaseScore")
                        .HasColumnType("float");

                    b.Property<double?>("CvssV2TemporalScore")
                        .HasColumnType("float");

                    b.Property<double?>("CvssV3BaseScore")
                        .HasColumnType("float");

                    b.Property<double?>("CvssV3TemporalScore")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("EpssScore")
                        .HasColumnType("float");

                    b.Property<int>("PluginId")
                        .HasColumnType("int");

                    b.Property<string>("PluginName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("References")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskFactor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Solution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StigSeverity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Synopsis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("VprScore")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PluginId");

                    b.HasIndex("Severity");

                    b.ToTable("VulnerabilityFindings");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.VulnerabilityInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetHostId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FirstFound")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastFound")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<string>("PluginOutput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Port")
                        .HasColumnType("int");

                    b.Property<string>("Protocol")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VulnerabilityFindingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetHostId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Status");

                    b.HasIndex("VulnerabilityFindingId");

                    b.ToTable("VulnerabilityInstances");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.AssetAuditTrail", b =>
                {
                    b.HasOne("VRTrackingApp.Data.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VRTrackingApp.Data.Models.UserAccount", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Asset");

                    b.Navigation("PerformedBy");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.AssetFieldChange", b =>
                {
                    b.HasOne("VRTrackingApp.Data.Models.AssetAuditTrail", "AssetAuditTrail")
                        .WithMany("FieldChanges")
                        .HasForeignKey("AssetAuditTrailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetAuditTrail");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.AssetHost", b =>
                {
                    b.HasOne("VRTrackingApp.Data.Models.Asset", "Asset")
                        .WithMany("ScanHosts")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VRTrackingApp.Data.Models.ScanUpload", "ScanUpload")
                        .WithMany("AssetHosts")
                        .HasForeignKey("ScanUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("ScanUpload");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.ExceptionRecord", b =>
                {
                    b.HasOne("VRTrackingApp.Data.Models.UserAccount", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById");

                    b.HasOne("VRTrackingApp.Data.Models.VulnerabilityInstance", "VulnerabilityInstance")
                        .WithOne("ExceptionRecord")
                        .HasForeignKey("VRTrackingApp.Data.Models.ExceptionRecord", "VulnerabilityInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("VulnerabilityInstance");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.RemediationAction", b =>
                {
                    b.HasOne("VRTrackingApp.Data.Models.UserAccount", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId");

                    b.HasOne("VRTrackingApp.Data.Models.UserAccount", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById");

                    b.HasOne("VRTrackingApp.Data.Models.VulnerabilityInstance", "VulnerabilityInstance")
                        .WithMany("RemediationActions")
                        .HasForeignKey("VulnerabilityInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("PerformedBy");

                    b.Navigation("VulnerabilityInstance");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.RemediationJob", b =>
                {
                    b.HasOne("VRTrackingApp.Data.Models.UserAccount", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VRTrackingApp.Data.Models.VulnerabilityInstance", "VulnerabilityInstance")
                        .WithMany()
                        .HasForeignKey("VulnerabilityInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedBy");

                    b.Navigation("VulnerabilityInstance");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.ScanUpload", b =>
                {
                    b.HasOne("VRTrackingApp.Data.Models.UserAccount", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.UploadAuditTrail", b =>
                {
                    b.HasOne("VRTrackingApp.Data.Models.UserAccount", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById");

                    b.HasOne("VRTrackingApp.Data.Models.ScanUpload", "ScanUpload")
                        .WithMany("AuditTrail")
                        .HasForeignKey("ScanUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformedBy");

                    b.Navigation("ScanUpload");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.UserAccount", b =>
                {
                    b.HasOne("VRTrackingApp.Data.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.VulnerabilityInstance", b =>
                {
                    b.HasOne("VRTrackingApp.Data.Models.AssetHost", "AssetHost")
                        .WithMany("Instances")
                        .HasForeignKey("AssetHostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VRTrackingApp.Data.Models.UserAccount", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.HasOne("VRTrackingApp.Data.Models.VulnerabilityFinding", "VulnerabilityFinding")
                        .WithMany("Instances")
                        .HasForeignKey("VulnerabilityFindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetHost");

                    b.Navigation("Owner");

                    b.Navigation("VulnerabilityFinding");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.Asset", b =>
                {
                    b.Navigation("ScanHosts");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.AssetAuditTrail", b =>
                {
                    b.Navigation("FieldChanges");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.AssetHost", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.ScanUpload", b =>
                {
                    b.Navigation("AssetHosts");

                    b.Navigation("AuditTrail");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.VulnerabilityFinding", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("VRTrackingApp.Data.Models.VulnerabilityInstance", b =>
                {
                    b.Navigation("ExceptionRecord");

                    b.Navigation("RemediationActions");
                });
#pragma warning restore 612, 618
        }
    }
}
